#rapids:
#  core:
#    database:
#      driverURL: jdbc:mysql://125.39.110.20:3306/memory_study?useUnicode=true&characterEncoding=UTF-8
#      userName: rapids
#      password: rps888#$%
#      initialSize: 3
#      minIdle: 3
#      maxActive: 30

rapids:
  core:
    database:
      driverURL: jdbc:mysql://localhost:3306/memory_study?useUnicode=true&characterEncoding=UTF-8
      userName: root
      password:
      initialSize: 3
      minIdle: 3
      maxActive: 30

file:
  upload:
#    path: /Users/scott/apache-tomcat-7.0.57/webapps/upload/
    path: /Users/scott/Github/rapids/management/static/img/upload/
  download:
    url: http://localhost/rapids-img/upload/
