server:
  context-path: /rapids
  port: 8082
rapids:
  core:
    database:
      driverURL: jdbc:mysql://125.39.110.20:3306/memory_study?useUnicode=true&characterEncoding=UTF-8
      userName: rapids
      password: rps888#$%
      initialSize: 3
      minIdle: 3
      maxActive: 30