server:
  context-path: /rapids-rest
  port: 8850
study:
#每天激活个数
  enableCount: 50
rapids:
  core:
    database:
#      driverURL: jdbc:mysql://125.39.110.20:3306/memory_study?useUnicode=true&characterEncoding=UTF-8
#      userName: rapids
#      password: rps888#$%
      driverURL: jdbc:mysql://localhost:3306/memory_study?useUnicode=true&characterEncoding=UTF-8
      userName: root
      initialSize: 3
      minIdle: 3
      maxActive: 30